---
- name: Installer les éditeurs de code
  become: true
  ansible.builtin.dnf:
    name: "{{ item.name }}"
    state: present
  loop: "{{ editors }}"
  when: item.enabled

- name: Désinstaller VSCodium si désactivé
  become: true
  ansible.builtin.dnf:
    name: codium
    state: absent
  when: not install_vscodium

- name: Désinstaller VSCode Insiders si désactivé
  become: true
  ansible.builtin.dnf:
    name: code-insiders
    state: absent
  when: not install_vscode_insiders
