---
- name: Installer VSCode
  become: true
  ansible.builtin.dnf:
    name: code
    state: present

- name: Créer le dossier de configuration VSCode
  ansible.builtin.file:
    path: "{{ vscode_settings_file | dirname }}"
    state: directory
    mode: '0755'

- name: Générer settings.json VSCode
  ansible.builtin.template:
    src: "settings.json.j2"
    dest: "{{ vscode_settings_file }}"
    mode: '0644'
