---
- name: Installer .vimrc personnalisé
  ansible.builtin.copy:
    src: vimrc
    dest: "{{ ansible_facts.env.HOME }}/.vimrc"
    owner: "{{ ansible_facts.env.USER }}"
    group: "{{ ansible_facts.env.USER }}"
    mode: '0644'
    backup: true
