---
- name: Mise à jour du cache DNF
  become: true
  ansible.builtin.dnf:
    update_cache: true

- name: Installation des paquets système
  become: true
  ansible.builtin.dnf:
    name: "{{ user_env_packages }}"
    state: present
